repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Updated to a more recent version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 24.4.2 # Updated to a more recent version
    hooks:
      - id: black
        args: [--line-length=88]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4 # Updated to a more recent version
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format # It's also good practice to let ruff handle formatting if desired

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0 # Updated to a more recent version
    hooks:
      - id: mypy
        # By removing the 'args', mypy will automatically use the stricter
        # configuration from your pyproject.toml file, ensuring consistency.
