# docker-compose.yml
# Orchestrates all services for the brAInwav MAS project environment.
# Run with: docker-compose up -d

services:
  # The Next.js frontend service for the learning platform
  frontend:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
    container_name: brainwav-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-next:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - brainwav-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # The Python backend service, where you will do most of your development.
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brainwav-backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/workspace
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      ollama:
        condition: service_started
    networks:
      - brainwav-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: >
      sh -c "uvicorn backend.src.main:app --host 0.0.0.0 --port 8000 --reload"

  # A PostgreSQL database service for persistent data storage.
  db:
    image: postgres:15-alpine
    container_name: brainwav-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - brainwav-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # The Ollama service for running local LLMs.
  ollama:
    image: ollama/ollama:latest
    container_name: brainwav-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - brainwav-net

# Named volumes for persistent data storage.
volumes:
  postgres_data:
  ollama_data:

# A dedicated network for services to communicate with each other.
networks:
  brainwav-net:
    driver: bridge
