# docker-compose.dev.yml — overrides for local hot‑reload
# ─────────────────────────────────────────────────────────────────────────────
# Combine with the base file:
#   docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
version: "3.8"

services:
  api:
    # Hot‑reload backend code from the host
    volumes:
      - ./:/workspace
    working_dir: /workspace/apps/api
    environment:
      PYTHONUNBUFFERED: "1" # flush logs immediately
    command: >-
      uv run uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    networks: [brainwav-net]

  # Optional: Next.js dev server
  web:
    profiles: [dev] # only starts with `--profile dev`
    build:
      context: apps/web
      dockerfile: Dockerfile.dev # lightweight Node image
    volumes:
      - ./apps/web:/workspace
    working_dir: /workspace
    command: pnpm dev --host 0.0.0.0
    ports:
      - "3000:3000"
    depends_on: [api]
    networks: [brainwav-net]
