services:
  # MCP Database Server
  mcp-db:
    image: postgres:16-alpine
    container_name: brainwav-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: brainwav_user
      POSTGRES_PASSWORD: brainwav_password # Note: For development only, use secrets in production
      POSTGRES_DB: brainwav_db
    volumes:
      - brainwav_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U brainwav_user -d brainwav_db']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mcp-network

  # Custom MCP Server (example Node.js server)
  mcp-custom:
    build:
      context: ./mcp-servers/custom
      dockerfile: Dockerfile
    container_name: mcp-custom
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: mcp-db
      DB_USER: brainwav_user
      DB_PASSWORD: brainwav_password
      DB_NAME: brainwav_db
    ports:
      - '3333:3333'
    depends_on:
      - mcp-db
    volumes:
      - ./mcp-servers/custom:/app
      - /app/node_modules
    networks:
      - mcp-network

volumes:
  brainwav_postgres_data:
    name: brainwav_postgres_data

networks:
  mcp-network:
    name: mcp-network
