services:
  # FastAPI backend service
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: brainwav-api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://brainwav_user:brainwav_password@brainwav-db:5432/brainwav_db
    ports:
      - '8000:8000'
    depends_on:
      brainwav-db:
        condition: service_healthy
    networks:
      - brainwav-net

  # Database service for brAInwav
  brainwav-db:
    image: postgres:16-alpine
    container_name: brainwav-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: brainwav_user
      POSTGRES_PASSWORD: brainwav_password # Note: For development only, use secrets in production
      POSTGRES_DB: brainwav_db
    volumes:
      - brainwav_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U brainwav_user -d brainwav_db']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - brainwav-net

  # Custom MCP Server (Node.js server for custom MCP tools)
  mcp-custom:
    build:
      context: ./mcp-servers/custom
      dockerfile: Dockerfile
    container_name: mcp-custom
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: brainwav-db
      DB_USER: brainwav_user
      DB_PASSWORD: brainwav_password
      DB_NAME: brainwav_db
      PYTHON_PATH: /usr/bin/python3
    ports:
      - '3333:3333'
    depends_on:
      brainwav-db:
        condition: service_healthy
    volumes:
      - ./mcp-servers/custom:/app
      - ./dist:/app/dist
      - /app/node_modules
    networks:
      - brainwav-net

volumes:
  brainwav_postgres_data:
    name: brainwav_postgres_data

networks:
  brainwav-net:
    name: brainwav-net
