services:
  # ...existing code...

volumes:
  # ...existing code... (consolidate all volume definitions here)

networks:
  # ...existing code... (consolidate all network definitions here)
  # ... all volume definitions
