# Root-level pyproject.toml (meta‑repo only)
# ─────────────────────────────────────────────────────────────────────────────
# This file is *not* a Python package. It exists purely to host shared tooling
# configuration for the brAInwav MAS monorepo. All buildable apps have their
# own pyproject.toml under ./apps/* or ./packages/*.

# ─── Shared UV settings ──────────────────────────────────────────────────────
[tool.uv]
# Example: path = "~/.cache/uv/shared-env"

# ─── Ruff ─────────────────────────────────────────────────────────────────────
[tool.ruff]
line-length = 100
select = ["E", "W", "F", "I"]
target-version = "py311"

# ─── Black ────────────────────────────────────────────────────────────────────
[tool.black]
line-length = 100
target-version = ["py311"]

# ─── isort ────────────────────────────────────────────────────────────────────
[tool.isort]
profile = "black"
line_length = 100
