name: 🐛 Bug Report
description: Report broken links, errors, or issues
title: "[BUG] "
labels: ["bug", "needs-investigation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! This helps keep the roadmap accurate and useful.

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of issue are you reporting?
      options:
        - Broken Link
        - JSON/Data Error
        - UI/Frontend Issue
        - Incorrect Information
        - Missing Resource
        - Performance Issue
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Clear description of what's wrong
      placeholder: "The issue is..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: "I expected..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Instead, what happens is..."
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL (if applicable)
      description: Link to the problematic resource or page
      placeholder: "https://example.com"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information
      placeholder: "Additional details..."
