name: Bug Report
description: Report a bug
body:
  - type: textarea
    id: bug
    attributes:
      label: Bug Description
      description: Describe the bug in detail.
      placeholder: Bug details here
    validations:
      required: true
