name: Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  project-validation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Project Structure Validation
      run: |
        # Check for test files in wrong location
        if find . -maxdepth 1 -name "test_*.py" | grep -q .; then
          echo "ERROR: Test files found in root directory, must be in tests/ directory"
          find . -maxdepth 1 -name "test_*.py"
          exit 1
        fi

        # Check for report files in wrong location
        if find . -maxdepth 1 \( -name "*.html" -o -name "*.xml" \) | grep -E "(coverage|report)" | grep -q .; then
          echo "ERROR: Report files found in root directory, must be in reports/ directory"
          find . -maxdepth 1 \( -name "*.html" -o -name "*.xml" \) | grep -E "(coverage|report)"
          exit 1
        fi

        echo "✅ Project structure validation passed"

    - name: Check for required files
      run: |
        required_files=(
          "README.md"
          "pyproject.toml"
          ".ai/AGENT.md"
          "backend/src/main.py"
          "backend/requirements.txt"
          "frontend/package.json"
        )

        missing_files=()
        for file in "${required_files[@]}"; do
          if [ ! -f "$file" ]; then
            missing_files+=("$file")
          fi
        done

        if [ ${#missing_files[@]} -ne 0 ]; then
          echo "ERROR: Missing required files:"
          printf '%s\n' "${missing_files[@]}"
          exit 1
        fi

        echo "✅ All required files present"
